org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false

# Mod Properties
mod_id=unai_bridge
mod_name=UnAI Bridge
mod_license=MIT
mod_version=1.0.0
mod_group_id=xyz.kasperstudios.unai
mod_authors=kasper-studios
mod_description=Native UnAI Minecraft Server Bridge for Forge 1.21.1

# Minecraft & Forge Versions
minecraft_version=1.21.1
forge_version=52.1.16
